# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# Backend

gem 'rails', '~> 5.1.1'
gem 'pg'
gem 'puma', '~> 3.7'
gem 'redis',   '~>3.2'
gem 'hiredis', '~> 0.6.0'
gem 'xxhash'
gem 'sidekiq'
gem 'sidekiq-scheduler'

# Frontend
gem 'haml-rails'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'
gem 'jquery-rails'
gem 'popper_js', '~> 1.12.3'
gem 'bootstrap', '~> 4.0.0.beta2.1'
gem 'bootstrap-generators', '~> 3.3.4'
gem 'bootstrap_forms'
gem 'will_paginate', '~> 3.1.0'
gem 'react-rails'
gem 'font-awesome-rails'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'selenium-webdriver'
  gem 'factory_girl_rails'
  gem 'rspec-rails'
  gem 'faker', :git => 'https://github.com/stympy/faker.git', :branch => 'master'
  gem 'mocha'
  gem 'database_cleaner'
end

group :development do
  gem 'rubocop', '~> 0.51.0', require: false
  gem 'overcommit', require: false
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'web-console', '>= 3.3.0'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
